version: '3.7'
services:
  apigateway:
    build:
      context: ../ApiGateway
    container_name: apigateway
    ports:
      - "8084:8084"
    depends_on:
      - configserver
      - serviceregistry

  configserver:
    build:
      context: ../ConfigServer
    container_name: configserver
    ports:
      - "8085:8085"

  hotelservice:
    build:
      context: ../HotelService
    container_name: hotelservice
    ports:
      - "8082:8082"
    depends_on:
      - serviceregistry
      - configserver

  ratingservice:
    build:
      context: ../RatingService
    container_name: ratingservice
    ports:
      - "8083:8083"
    depends_on:
      - serviceregistry
      - configserver

  serviceregistry:
    build:
      context: ../ServiceRegistry
    container_name: serviceregistry
    ports:
      - "8761:8761"

  userservice:
    build:
      context: ../UserService
    container_name: userservice
    ports:
      - "8081:8081"
    depends_on:
      - serviceregistry
      - configserver
