server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
    
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  
#to take the below commented configurations from Config server    
  config:
     import: configserver:http://sudhirs.mkclad.mkcl.org:8085 

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    