server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  config:
    import: configserver:http://sudhirs.mkclad.mkcl.org:8085

  profiles:
    active: dev

# Uncomment these lines if needed if you dont want configurations from config server
# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka

# Configuration of actuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

# Configuration of circuit-breaker in resilience-4j
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:    
        registerHealthIndicator: true    #name given in controller and registering above actuator with circuit breaker
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        
  # Configuration of Retry-module in resilience-4j      
  retry:
    instances:
      ratingHotelService: #name of retry module given in controller
        max-attempts: 3
        wait-duration: 5s
    
  # Configuration of Rate-Limiter in resilience-4j      
  ratelimiter:
    instances:
      userRateLimiter:     #name of Rate-Limiter given in controller
        limit-refresh-period: 4s
        limit-for-period: 2  
        timeout-duration: 2s
